### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by mwaseem-defendai** [Defend-AI-Tech-Inc/wozway#1]
When following instructions, the script ran into an error:

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/hn/twmm88w104xbgn9vw2qwf9vc0000gq/T/pip-build-env-b3292ldq/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

Tried multiple updates to different libraries... with no luck. 
Env: Python 3.12.7
reinstalled jinja2..

**Comment by mwaseem-defendai** [comment]
To resolve this update the requirements.txt with PyYAML==6.0.1 This will resolve the issue and complete the installation.

**Comment by AidaHelix** [comment]
Fixed
